/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AttachmentList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class AttachmentList {
    @SerializedName("total")
    private Integer total = null;

    @SerializedName("attachments")
    private List<Attachment> attachments = new ArrayList<Attachment>();

    public AttachmentList total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * 总数
     *
     * @return total
     **/
    @ApiModelProperty(example = "null", value = "总数")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public AttachmentList attachments(List<Attachment> attachments) {
        this.attachments = attachments;
        return this;
    }

    public AttachmentList addAttachmentsItem(Attachment attachmentsItem) {
        this.attachments.add(attachmentsItem);
        return this;
    }

    /**
     * 附件列表
     *
     * @return attachments
     **/
    @ApiModelProperty(example = "null", value = "附件列表")
    public List<Attachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AttachmentList attachmentList = (AttachmentList) o;
        return Objects.equals(this.total, attachmentList.total) &&
                Objects.equals(this.attachments, attachmentList.attachments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(total, attachments);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AttachmentList {\n");

        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

