/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ContactRelation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class ContactRelation {
    @SerializedName("mailboxId")
    private String mailboxId = null;

    @SerializedName("to")
    private String to = null;

    @SerializedName("count")
    private Integer count = null;

    public ContactRelation mailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
        return this;
    }

    /**
     * 邮箱Id
     *
     * @return mailboxId
     **/
    @ApiModelProperty(example = "null", value = "邮箱Id")
    public String getMailboxId() {
        return mailboxId;
    }

    public void setMailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
    }

    public ContactRelation to(String to) {
        this.to = to;
        return this;
    }

    /**
     * 关系人
     *
     * @return to
     **/
    @ApiModelProperty(example = "null", value = "关系人")
    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public ContactRelation count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * 来往邮件数
     *
     * @return count
     **/
    @ApiModelProperty(example = "null", value = "来往邮件数")
    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContactRelation contactRelation = (ContactRelation) o;
        return Objects.equals(this.mailboxId, contactRelation.mailboxId) &&
                Objects.equals(this.to, contactRelation.to) &&
                Objects.equals(this.count, contactRelation.count);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mailboxId, to, count);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ContactRelation {\n");

        sb.append("    mailboxId: ").append(toIndentedString(mailboxId)).append("\n");
        sb.append("    to: ").append(toIndentedString(to)).append("\n");
        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

