/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ContactList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class ContactList {
    @SerializedName("total")
    private Integer total = null;

    @SerializedName("contacts")
    private List<ContactItem> contacts = new ArrayList<ContactItem>();

    public ContactList total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * 总数
     *
     * @return total
     **/
    @ApiModelProperty(example = "null", value = "总数")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public ContactList contacts(List<ContactItem> contacts) {
        this.contacts = contacts;
        return this;
    }

    public ContactList addContactsItem(ContactItem contactsItem) {
        this.contacts.add(contactsItem);
        return this;
    }

    /**
     * 联系人列表
     *
     * @return contacts
     **/
    @ApiModelProperty(example = "null", value = "联系人列表")
    public List<ContactItem> getContacts() {
        return contacts;
    }

    public void setContacts(List<ContactItem> contacts) {
        this.contacts = contacts;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContactList contactList = (ContactList) o;
        return Objects.equals(this.total, contactList.total) &&
                Objects.equals(this.contacts, contactList.contacts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(total, contacts);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ContactList {\n");

        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

