/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Contact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class Contact {
    @SerializedName("contactId")
    private String contactId = null;

    @SerializedName("contactName")
    private String contactName = null;

    @SerializedName("contactMailAddr")
    private String contactMailAddr = null;

    @SerializedName("associateCount")
    private Long associateCount = null;

    @SerializedName("tag")
    private String tag = null;

    @SerializedName("note")
    private String note = null;

    public Contact contactId(String contactId) {
        this.contactId = contactId;
        return this;
    }

    /**
     * 联系人Id
     *
     * @return contactId
     **/
    @ApiModelProperty(example = "null", value = "联系人Id")
    public String getContactId() {
        return contactId;
    }

    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    public Contact contactName(String contactName) {
        this.contactName = contactName;
        return this;
    }

    /**
     * 联系人名称
     *
     * @return contactName
     **/
    @ApiModelProperty(example = "null", value = "联系人名称")
    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public Contact contactMailAddr(String contactMailAddr) {
        this.contactMailAddr = contactMailAddr;
        return this;
    }

    /**
     * 联系人邮箱地址
     *
     * @return contactMailAddr
     **/
    @ApiModelProperty(example = "null", value = "联系人邮箱地址")
    public String getContactMailAddr() {
        return contactMailAddr;
    }

    public void setContactMailAddr(String contactMailAddr) {
        this.contactMailAddr = contactMailAddr;
    }

    public Contact associateCount(Long associateCount) {
        this.associateCount = associateCount;
        return this;
    }

    /**
     * 相关联系人数量
     *
     * @return associateCount
     **/
    @ApiModelProperty(example = "null", value = "相关联系人数量")
    public Long getAssociateCount() {
        return associateCount;
    }

    public void setAssociateCount(Long associateCount) {
        this.associateCount = associateCount;
    }

    public Contact tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * 标签
     *
     * @return tag
     **/
    @ApiModelProperty(example = "null", value = "标签")
    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Contact note(String note) {
        this.note = note;
        return this;
    }

    /**
     * 批注
     *
     * @return note
     **/
    @ApiModelProperty(example = "null", value = "批注")
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Contact contact = (Contact) o;
        return Objects.equals(this.contactId, contact.contactId) &&
                Objects.equals(this.contactName, contact.contactName) &&
                Objects.equals(this.contactMailAddr, contact.contactMailAddr) &&
                Objects.equals(this.associateCount, contact.associateCount) &&
                Objects.equals(this.tag, contact.tag) &&
                Objects.equals(this.note, contact.note);
    }

    @Override
    public int hashCode() {
        return Objects.hash(contactId, contactName, contactMailAddr, associateCount, tag, note);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Contact {\n");

        sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
        sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
        sb.append("    contactMailAddr: ").append(toIndentedString(contactMailAddr)).append("\n");
        sb.append("    associateCount: ").append(toIndentedString(associateCount)).append("\n");
        sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("    note: ").append(toIndentedString(note)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

