/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * LoadState
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class LoadState {
    @SerializedName("progressLabel")
    private String progressLabel = null;

    @SerializedName("totalCount")
    private Long totalCount = null;

    @SerializedName("successCount")
    private Long successCount = null;

    @SerializedName("failCount")
    private Long failCount = null;

    @SerializedName("failFiles")
    private List<String> failFiles = new ArrayList<String>();

    public LoadState progressLabel(String progressLabel) {
        this.progressLabel = progressLabel;
        return this;
    }

    /**
     * 装载状态文本
     *
     * @return progressLabel
     **/
    @ApiModelProperty(example = "null", value = "装载状态文本")
    public String getProgressLabel() {
        return progressLabel;
    }

    public void setProgressLabel(String progressLabel) {
        this.progressLabel = progressLabel;
    }

    public LoadState totalCount(Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }

    /**
     * 数据文件总量
     *
     * @return totalCount
     **/
    @ApiModelProperty(example = "null", value = "数据文件总量")
    public Long getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }

    public LoadState successCount(Long successCount) {
        this.successCount = successCount;
        return this;
    }

    /**
     * 装载成功数量
     *
     * @return successCount
     **/
    @ApiModelProperty(example = "null", value = "装载成功数量")
    public Long getSuccessCount() {
        return successCount;
    }

    public void setSuccessCount(Long successCount) {
        this.successCount = successCount;
    }

    public LoadState failCount(Long failCount) {
        this.failCount = failCount;
        return this;
    }

    /**
     * 装载失败数量
     *
     * @return failCount
     **/
    @ApiModelProperty(example = "null", value = "装载失败数量")
    public Long getFailCount() {
        return failCount;
    }

    public void setFailCount(Long failCount) {
        this.failCount = failCount;
    }

    public LoadState failFiles(List<String> failFiles) {
        this.failFiles = failFiles;
        return this;
    }

    public LoadState addFailFilesItem(String failFilesItem) {
        this.failFiles.add(failFilesItem);
        return this;
    }

    /**
     * 装载失败的文件路径列表
     *
     * @return failFiles
     **/
    @ApiModelProperty(example = "null", value = "装载失败的文件路径列表")
    public List<String> getFailFiles() {
        return failFiles;
    }

    public void setFailFiles(List<String> failFiles) {
        this.failFiles = failFiles;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LoadState loadState = (LoadState) o;
        return Objects.equals(this.progressLabel, loadState.progressLabel) &&
                Objects.equals(this.totalCount, loadState.totalCount) &&
                Objects.equals(this.successCount, loadState.successCount) &&
                Objects.equals(this.failCount, loadState.failCount) &&
                Objects.equals(this.failFiles, loadState.failFiles);
    }

    @Override
    public int hashCode() {
        return Objects.hash(progressLabel, totalCount, successCount, failCount, failFiles);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LoadState {\n");

        sb.append("    progressLabel: ").append(toIndentedString(progressLabel)).append("\n");
        sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
        sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
        sb.append("    failCount: ").append(toIndentedString(failCount)).append("\n");
        sb.append("    failFiles: ").append(toIndentedString(failFiles)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

