/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MailList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class MailList {
    @SerializedName("mailboxName")
    private String mailboxName = null;

    @SerializedName("total")
    private Integer total = null;

    @SerializedName("mails")
    private List<Mail> mails = new ArrayList<Mail>();

    public MailList mailboxName(String mailboxName) {
        this.mailboxName = mailboxName;
        return this;
    }

    /**
     * 邮箱名称 - INBOX - OUTBOX - DRAFTBOXBOX - TRASHBOX
     *
     * @return mailboxName
     **/
    @ApiModelProperty(example = "null", value = "邮箱名称 - INBOX - OUTBOX - DRAFTBOXBOX - TRASHBOX")
    public String getMailboxName() {
        return mailboxName;
    }

    public void setMailboxName(String mailboxName) {
        this.mailboxName = mailboxName;
    }

    public MailList total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * 邮箱中邮件的数量
     *
     * @return total
     **/
    @ApiModelProperty(example = "null", value = "邮箱中邮件的数量")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public MailList mails(List<Mail> mails) {
        this.mails = mails;
        return this;
    }

    public MailList addMailsItem(Mail mailsItem) {
        this.mails.add(mailsItem);
        return this;
    }

    /**
     * 邮箱中的邮件
     *
     * @return mails
     **/
    @ApiModelProperty(example = "null", value = "邮箱中的邮件")
    public List<Mail> getMails() {
        return mails;
    }

    public void setMails(List<Mail> mails) {
        this.mails = mails;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MailList mailList = (MailList) o;
        return Objects.equals(this.mailboxName, mailList.mailboxName) &&
                Objects.equals(this.total, mailList.total) &&
                Objects.equals(this.mails, mailList.mails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mailboxName, total, mails);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MailList {\n");

        sb.append("    mailboxName: ").append(toIndentedString(mailboxName)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    mails: ").append(toIndentedString(mails)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

