/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Mail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class Mail {
    @SerializedName("mailId")
    private String mailId = null;

    @SerializedName("mailboxId")
    private String mailboxId = null;

    @SerializedName("from")
    private String from = null;

    @SerializedName("fromName")
    private String fromName = null;

    @SerializedName("subject")
    private String subject = null;

    @SerializedName("to")
    private String to = null;

    @SerializedName("cc")
    private String cc = null;

    @SerializedName("bcc")
    private String bcc = null;

    @SerializedName("sendTime")
    private Long sendTime = null;

    @SerializedName("sendTimezone")
    private Integer sendTimezone = null;

    @SerializedName("mailContent")
    private String mailContent = null;

    @SerializedName("sessionCount")
    private Integer sessionCount = null;

    @SerializedName("attachmentCount")
    private Integer attachmentCount = null;

    @SerializedName("tagCount")
    private Integer tagCount = null;

    @SerializedName("sysTagCount")
    private Integer sysTagCount = null;

    @SerializedName("tag")
    private String tag = null;

    @SerializedName("note")
    private String note = null;

    @SerializedName("remark")
    private String remark = null;

    @SerializedName("attachments")
    private List<Attachment> attachments = new ArrayList<Attachment>();

    public Mail mailId(String mailId) {
        this.mailId = mailId;
        return this;
    }

    /**
     * Get mailId
     *
     * @return mailId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getMailId() {
        return mailId;
    }

    public void setMailId(String mailId) {
        this.mailId = mailId;
    }

    public Mail mailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
        return this;
    }

    /**
     * 邮箱
     *
     * @return mailboxId
     **/
    @ApiModelProperty(example = "null", value = "邮箱")
    public String getMailboxId() {
        return mailboxId;
    }

    public void setMailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
    }

    public Mail from(String from) {
        this.from = from;
        return this;
    }

    /**
     * 发件人
     *
     * @return from
     **/
    @ApiModelProperty(example = "null", value = "发件人")
    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public Mail fromName(String fromName) {
        this.fromName = fromName;
        return this;
    }

    /**
     * 发件人姓名
     *
     * @return fromName
     **/
    @ApiModelProperty(example = "null", value = "发件人姓名")
    public String getFromName() {
        return fromName;
    }

    public void setFromName(String fromName) {
        this.fromName = fromName;
    }

    public Mail subject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * 主题
     *
     * @return subject
     **/
    @ApiModelProperty(example = "null", value = "主题")
    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Mail to(String to) {
        this.to = to;
        return this;
    }

    /**
     * 收件人
     *
     * @return to
     **/
    @ApiModelProperty(example = "null", value = "收件人")
    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public Mail cc(String cc) {
        this.cc = cc;
        return this;
    }

    /**
     * 抄送
     *
     * @return cc
     **/
    @ApiModelProperty(example = "null", value = "抄送")
    public String getCc() {
        return cc;
    }

    public void setCc(String cc) {
        this.cc = cc;
    }

    public Mail bcc(String bcc) {
        this.bcc = bcc;
        return this;
    }

    /**
     * 暗送
     *
     * @return bcc
     **/
    @ApiModelProperty(example = "null", value = "暗送")
    public String getBcc() {
        return bcc;
    }

    public void setBcc(String bcc) {
        this.bcc = bcc;
    }

    public Mail sendTime(Long sendTime) {
        this.sendTime = sendTime;
        return this;
    }

    /**
     * 发送时间
     *
     * @return sendTime
     **/
    @ApiModelProperty(example = "null", value = "发送时间")
    public Long getSendTime() {
        return sendTime;
    }

    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    public Mail sendTimezone(Integer sendTimezone) {
        this.sendTimezone = sendTimezone;
        return this;
    }

    /**
     * 发送时区
     *
     * @return sendTimezone
     **/
    @ApiModelProperty(example = "null", value = "发送时区")
    public Integer getSendTimezone() {
        return sendTimezone;
    }

    public void setSendTimezone(Integer sendTimezone) {
        this.sendTimezone = sendTimezone;
    }

    public Mail mailContent(String mailContent) {
        this.mailContent = mailContent;
        return this;
    }

    /**
     * 邮件内容
     *
     * @return mailContent
     **/
    @ApiModelProperty(example = "null", value = "邮件内容")
    public String getMailContent() {
        return mailContent;
    }

    public void setMailContent(String mailContent) {
        this.mailContent = mailContent;
    }

    public Mail sessionCount(Integer sessionCount) {
        this.sessionCount = sessionCount;
        return this;
    }

    /**
     * 会话数量
     *
     * @return sessionCount
     **/
    @ApiModelProperty(example = "null", value = "会话数量")
    public Integer getSessionCount() {
        return sessionCount;
    }

    public void setSessionCount(Integer sessionCount) {
        this.sessionCount = sessionCount;
    }

    public Mail attachmentCount(Integer attachmentCount) {
        this.attachmentCount = attachmentCount;
        return this;
    }

    /**
     * 附件数量
     *
     * @return attachmentCount
     **/
    @ApiModelProperty(example = "null", value = "附件数量")
    public Integer getAttachmentCount() {
        return attachmentCount;
    }

    public void setAttachmentCount(Integer attachmentCount) {
        this.attachmentCount = attachmentCount;
    }

    public Mail tagCount(Integer tagCount) {
        this.tagCount = tagCount;
        return this;
    }

    /**
     * 标签数量
     *
     * @return tagCount
     **/
    @ApiModelProperty(example = "null", value = "标签数量")
    public Integer getTagCount() {
        return tagCount;
    }

    public void setTagCount(Integer tagCount) {
        this.tagCount = tagCount;
    }

    public Mail sysTagCount(Integer sysTagCount) {
        this.sysTagCount = sysTagCount;
        return this;
    }

    /**
     * 初始系统标签数量
     *
     * @return sysTagCount
     **/
    @ApiModelProperty(example = "null", value = "初始系统标签数量")
    public Integer getSysTagCount() {
        return sysTagCount;
    }

    public void setSysTagCount(Integer sysTagCount) {
        this.sysTagCount = sysTagCount;
    }

    public Mail tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * 自定义标签字符串：name1,name2,name3
     *
     * @return tag
     **/
    @ApiModelProperty(example = "null", value = "自定义标签字符串：name1,name2,name3")
    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Mail note(String note) {
        this.note = note;
        return this;
    }

    /**
     * 批注
     *
     * @return note
     **/
    @ApiModelProperty(example = "null", value = "批注")
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Mail remark(String remark) {
        this.remark = remark;
        return this;
    }

    /**
     * 备注
     *
     * @return remark
     **/
    @ApiModelProperty(example = "null", value = "备注")
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Mail attachments(List<Attachment> attachments) {
        this.attachments = attachments;
        return this;
    }

    public Mail addAttachmentsItem(Attachment attachmentsItem) {
        this.attachments.add(attachmentsItem);
        return this;
    }

    /**
     * 附件列表
     *
     * @return attachments
     **/
    @ApiModelProperty(example = "null", value = "附件列表")
    public List<Attachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Mail mail = (Mail) o;
        return Objects.equals(this.mailId, mail.mailId) &&
                Objects.equals(this.mailboxId, mail.mailboxId) &&
                Objects.equals(this.from, mail.from) &&
                Objects.equals(this.fromName, mail.fromName) &&
                Objects.equals(this.subject, mail.subject) &&
                Objects.equals(this.to, mail.to) &&
                Objects.equals(this.cc, mail.cc) &&
                Objects.equals(this.bcc, mail.bcc) &&
                Objects.equals(this.sendTime, mail.sendTime) &&
                Objects.equals(this.sendTimezone, mail.sendTimezone) &&
                Objects.equals(this.mailContent, mail.mailContent) &&
                Objects.equals(this.sessionCount, mail.sessionCount) &&
                Objects.equals(this.attachmentCount, mail.attachmentCount) &&
                Objects.equals(this.tagCount, mail.tagCount) &&
                Objects.equals(this.sysTagCount, mail.sysTagCount) &&
                Objects.equals(this.tag, mail.tag) &&
                Objects.equals(this.note, mail.note) &&
                Objects.equals(this.remark, mail.remark) &&
                Objects.equals(this.attachments, mail.attachments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mailId, mailboxId, from, fromName, subject, to, cc, bcc, sendTime, sendTimezone, mailContent, sessionCount, attachmentCount, tagCount, sysTagCount, tag, note, remark, attachments);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Mail {\n");

        sb.append("    mailId: ").append(toIndentedString(mailId)).append("\n");
        sb.append("    mailboxId: ").append(toIndentedString(mailboxId)).append("\n");
        sb.append("    from: ").append(toIndentedString(from)).append("\n");
        sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
        sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
        sb.append("    to: ").append(toIndentedString(to)).append("\n");
        sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
        sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
        sb.append("    sendTime: ").append(toIndentedString(sendTime)).append("\n");
        sb.append("    sendTimezone: ").append(toIndentedString(sendTimezone)).append("\n");
        sb.append("    mailContent: ").append(toIndentedString(mailContent)).append("\n");
        sb.append("    sessionCount: ").append(toIndentedString(sessionCount)).append("\n");
        sb.append("    attachmentCount: ").append(toIndentedString(attachmentCount)).append("\n");
        sb.append("    tagCount: ").append(toIndentedString(tagCount)).append("\n");
        sb.append("    sysTagCount: ").append(toIndentedString(sysTagCount)).append("\n");
        sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("    note: ").append(toIndentedString(note)).append("\n");
        sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
        sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

