/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Mailbox
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class Mailbox {
    @SerializedName("mailboxId")
    private String mailboxId = null;

    @SerializedName("mailboxAddress")
    private String mailboxAddress = null;

    @SerializedName("inboxCount")
    private Integer inboxCount = null;

    @SerializedName("outboxCount")
    private Integer outboxCount = null;

    @SerializedName("draftboxCount")
    private Integer draftboxCount = null;

    @SerializedName("trashCount")
    private Integer trashCount = null;

    @SerializedName("tagCount")
    private Integer tagCount = null;

    @SerializedName("total")
    private Integer total = null;

    @SerializedName("tag")
    private String tag = null;

    @SerializedName("note")
    private String note = null;

    public Mailbox mailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
        return this;
    }

    /**
     * 邮箱id
     *
     * @return mailboxId
     **/
    @ApiModelProperty(example = "null", value = "邮箱id")
    public String getMailboxId() {
        return mailboxId;
    }

    public void setMailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
    }

    public Mailbox mailboxAddress(String mailboxAddress) {
        this.mailboxAddress = mailboxAddress;
        return this;
    }

    /**
     * 邮箱名称
     *
     * @return mailboxAddress
     **/
    @ApiModelProperty(example = "null", value = "邮箱名称")
    public String getMailboxAddress() {
        return mailboxAddress;
    }

    public void setMailboxAddress(String mailboxAddress) {
        this.mailboxAddress = mailboxAddress;
    }

    public Mailbox inboxCount(Integer inboxCount) {
        this.inboxCount = inboxCount;
        return this;
    }

    /**
     * 收件箱邮件数量
     *
     * @return inboxCount
     **/
    @ApiModelProperty(example = "null", value = "收件箱邮件数量")
    public Integer getInboxCount() {
        return inboxCount;
    }

    public void setInboxCount(Integer inboxCount) {
        this.inboxCount = inboxCount;
    }

    public Mailbox outboxCount(Integer outboxCount) {
        this.outboxCount = outboxCount;
        return this;
    }

    /**
     * 发件箱邮件数量
     *
     * @return outboxCount
     **/
    @ApiModelProperty(example = "null", value = "发件箱邮件数量")
    public Integer getOutboxCount() {
        return outboxCount;
    }

    public void setOutboxCount(Integer outboxCount) {
        this.outboxCount = outboxCount;
    }

    public Mailbox draftboxCount(Integer draftboxCount) {
        this.draftboxCount = draftboxCount;
        return this;
    }

    /**
     * 草稿箱邮件数量
     *
     * @return draftboxCount
     **/
    @ApiModelProperty(example = "null", value = "草稿箱邮件数量")
    public Integer getDraftboxCount() {
        return draftboxCount;
    }

    public void setDraftboxCount(Integer draftboxCount) {
        this.draftboxCount = draftboxCount;
    }

    public Mailbox trashCount(Integer trashCount) {
        this.trashCount = trashCount;
        return this;
    }

    /**
     * 垃圾箱邮件数量
     *
     * @return trashCount
     **/
    @ApiModelProperty(example = "null", value = "垃圾箱邮件数量")
    public Integer getTrashCount() {
        return trashCount;
    }

    public void setTrashCount(Integer trashCount) {
        this.trashCount = trashCount;
    }

    public Mailbox tagCount(Integer tagCount) {
        this.tagCount = tagCount;
        return this;
    }

    /**
     * 标签数量
     *
     * @return tagCount
     **/
    @ApiModelProperty(example = "null", value = "标签数量")
    public Integer getTagCount() {
        return tagCount;
    }

    public void setTagCount(Integer tagCount) {
        this.tagCount = tagCount;
    }

    public Mailbox total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * 总数
     *
     * @return total
     **/
    @ApiModelProperty(example = "null", value = "总数")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Mailbox tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * 标签
     *
     * @return tag
     **/
    @ApiModelProperty(example = "null", value = "标签")
    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Mailbox note(String note) {
        this.note = note;
        return this;
    }

    /**
     * 批注
     *
     * @return note
     **/
    @ApiModelProperty(example = "null", value = "批注")
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Mailbox mailbox = (Mailbox) o;
        return Objects.equals(this.mailboxId, mailbox.mailboxId) &&
                Objects.equals(this.mailboxAddress, mailbox.mailboxAddress) &&
                Objects.equals(this.inboxCount, mailbox.inboxCount) &&
                Objects.equals(this.outboxCount, mailbox.outboxCount) &&
                Objects.equals(this.draftboxCount, mailbox.draftboxCount) &&
                Objects.equals(this.trashCount, mailbox.trashCount) &&
                Objects.equals(this.tagCount, mailbox.tagCount) &&
                Objects.equals(this.total, mailbox.total) &&
                Objects.equals(this.tag, mailbox.tag) &&
                Objects.equals(this.note, mailbox.note);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mailboxId, mailboxAddress, inboxCount, outboxCount, draftboxCount, trashCount, tagCount, total, tag, note);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Mailbox {\n");

        sb.append("    mailboxId: ").append(toIndentedString(mailboxId)).append("\n");
        sb.append("    mailboxAddress: ").append(toIndentedString(mailboxAddress)).append("\n");
        sb.append("    inboxCount: ").append(toIndentedString(inboxCount)).append("\n");
        sb.append("    outboxCount: ").append(toIndentedString(outboxCount)).append("\n");
        sb.append("    draftboxCount: ").append(toIndentedString(draftboxCount)).append("\n");
        sb.append("    trashCount: ").append(toIndentedString(trashCount)).append("\n");
        sb.append("    tagCount: ").append(toIndentedString(tagCount)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("    note: ").append(toIndentedString(note)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

