/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PluginOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T07:16:57.704Z")
public class PluginOption {
    @SerializedName("optionKey")
    private String optionKey = null;

    @SerializedName("optionLabel")
    private String optionLabel = null;

    @SerializedName("optionValue")
    private String optionValue = null;

    public PluginOption optionKey(String optionKey) {
        this.optionKey = optionKey;
        return this;
    }

    /**
     * 配置项键名
     *
     * @return optionKey
     **/
    @ApiModelProperty(example = "null", value = "配置项键名")
    public String getOptionKey() {
        return optionKey;
    }

    public void setOptionKey(String optionKey) {
        this.optionKey = optionKey;
    }

    public PluginOption optionLabel(String optionLabel) {
        this.optionLabel = optionLabel;
        return this;
    }

    /**
     * 配置项名称
     *
     * @return optionLabel
     **/
    @ApiModelProperty(example = "null", value = "配置项名称")
    public String getOptionLabel() {
        return optionLabel;
    }

    public void setOptionLabel(String optionLabel) {
        this.optionLabel = optionLabel;
    }

    public PluginOption optionValue(String optionValue) {
        this.optionValue = optionValue;
        return this;
    }

    /**
     * 配置项键值
     *
     * @return optionValue
     **/
    @ApiModelProperty(example = "null", value = "配置项键值")
    public String getOptionValue() {
        return optionValue;
    }

    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PluginOption pluginOption = (PluginOption) o;
        return Objects.equals(this.optionKey, pluginOption.optionKey) &&
                Objects.equals(this.optionLabel, pluginOption.optionLabel) &&
                Objects.equals(this.optionValue, pluginOption.optionValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(optionKey, optionLabel, optionValue);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PluginOption {\n");

        sb.append("    optionKey: ").append(toIndentedString(optionKey)).append("\n");
        sb.append("    optionLabel: ").append(toIndentedString(optionLabel)).append("\n");
        sb.append("    optionValue: ").append(toIndentedString(optionValue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

