/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attribute', 'model/UseTag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Attribute'), require('./UseTag'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.AttachmentDetail = factory(root.CInsightGui.ApiClient, root.CInsightGui.Attribute, root.CInsightGui.UseTag);
  }
}(this, function(ApiClient, Attribute, UseTag) {
  'use strict';




  /**
   * The AttachmentDetail model module.
   * @module model/AttachmentDetail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AttachmentDetail</code>.
   * @alias module:model/AttachmentDetail
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>AttachmentDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttachmentDetail} obj Optional instance to populate.
   * @return {module:model/AttachmentDetail} The populated <code>AttachmentDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attachmentId')) {
        obj['attachmentId'] = ApiClient.convertToType(data['attachmentId'], 'String');
      }
      if (data.hasOwnProperty('attachmentName')) {
        obj['attachmentName'] = ApiClient.convertToType(data['attachmentName'], 'String');
      }
      if (data.hasOwnProperty('attachmentSize')) {
        obj['attachmentSize'] = ApiClient.convertToType(data['attachmentSize'], 'Number');
      }
      if (data.hasOwnProperty('attachmentContent')) {
        obj['attachmentContent'] = ApiClient.convertToType(data['attachmentContent'], 'Number');
      }
      if (data.hasOwnProperty('fileType')) {
        obj['fileType'] = ApiClient.convertToType(data['fileType'], 'String');
      }
      if (data.hasOwnProperty('filePath')) {
        obj['filePath'] = ApiClient.convertToType(data['filePath'], 'String');
      }
      if (data.hasOwnProperty('createTime')) {
        obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Number');
      }
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], [Attribute]);
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [UseTag]);
      }
      if (data.hasOwnProperty('notes')) {
        obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
      }
    }
    return obj;
  }

  /**
   * 附件id
   * @member {String} attachmentId
   */
  exports.prototype['attachmentId'] = undefined;
  /**
   * 附件名称
   * @member {String} attachmentName
   */
  exports.prototype['attachmentName'] = undefined;
  /**
   * 附件大小
   * @member {Number} attachmentSize
   */
  exports.prototype['attachmentSize'] = undefined;
  /**
   * 附件内容（图片路径）
   * @member {Number} attachmentContent
   */
  exports.prototype['attachmentContent'] = undefined;
  /**
   * 文件类型
   * @member {String} fileType
   */
  exports.prototype['fileType'] = undefined;
  /**
   * 文件路径
   * @member {String} filePath
   */
  exports.prototype['filePath'] = undefined;
  /**
   * 创建时间
   * @member {Number} createTime
   */
  exports.prototype['createTime'] = undefined;
  /**
   * 附件属性
   * @member {Array.<module:model/Attribute>} attributes
   */
  exports.prototype['attributes'] = undefined;
  /**
   * 标签列表
   * @member {Array.<module:model/UseTag>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * 批注内容
   * @member {String} notes
   */
  exports.prototype['notes'] = undefined;



  return exports;
}));


