/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.Attribute = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Attribute model module.
   * @module model/Attribute
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Attribute</code>.
   * @alias module:model/Attribute
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Attribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Attribute} obj Optional instance to populate.
   * @return {module:model/Attribute} The populated <code>Attribute</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('author')) {
        obj['author'] = ApiClient.convertToType(data['author'], 'String');
      }
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('gps')) {
        obj['gps'] = ApiClient.convertToType(data['gps'], 'String');
      }
      if (data.hasOwnProperty('camera')) {
        obj['camera'] = ApiClient.convertToType(data['camera'], 'String');
      }
      if (data.hasOwnProperty('shotTime')) {
        obj['shotTime'] = ApiClient.convertToType(data['shotTime'], 'String');
      }
    }
    return obj;
  }

  /**
   * 作者
   * @member {String} author
   */
  exports.prototype['author'] = undefined;
  /**
   * 公司
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * GPS
   * @member {String} gps
   */
  exports.prototype['gps'] = undefined;
  /**
   * 相机型号
   * @member {String} camera
   */
  exports.prototype['camera'] = undefined;
  /**
   * 拍摄时间
   * @member {String} shotTime
   */
  exports.prototype['shotTime'] = undefined;



  return exports;
}));


