/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.Condition = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Condition model module.
   * @module model/Condition
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Condition</code>.
   * @alias module:model/Condition
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Condition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Condition} obj Optional instance to populate.
   * @return {module:model/Condition} The populated <code>Condition</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('keyword')) {
        obj['keyword'] = ApiClient.convertToType(data['keyword'], 'String');
      }
      if (data.hasOwnProperty('expression')) {
        obj['expression'] = ApiClient.convertToType(data['expression'], 'String');
      }
      if (data.hasOwnProperty('result')) {
        obj['result'] = ApiClient.convertToType(data['result'], 'String');
      }
      if (data.hasOwnProperty('relation')) {
        obj['relation'] = ApiClient.convertToType(data['relation'], 'String');
      }
    }
    return obj;
  }

  /**
   * 关键词
   * @member {String} keyword
   */
  exports.prototype['keyword'] = undefined;
  /**
   * 表达式
   * @member {String} expression
   */
  exports.prototype['expression'] = undefined;
  /**
   * 条件值
   * @member {String} result
   */
  exports.prototype['result'] = undefined;
  /**
   * 条件关系
   * @member {String} relation
   */
  exports.prototype['relation'] = undefined;



  return exports;
}));


