/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactDetailRelation', 'model/Diagram', 'model/UseTag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContactDetailRelation'), require('./Diagram'), require('./UseTag'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.ContactDetail = factory(root.CInsightGui.ApiClient, root.CInsightGui.ContactDetailRelation, root.CInsightGui.Diagram, root.CInsightGui.UseTag);
  }
}(this, function(ApiClient, ContactDetailRelation, Diagram, UseTag) {
  'use strict';




  /**
   * The ContactDetail model module.
   * @module model/ContactDetail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ContactDetail</code>.
   * @alias module:model/ContactDetail
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ContactDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactDetail} obj Optional instance to populate.
   * @return {module:model/ContactDetail} The populated <code>ContactDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('relations')) {
        obj['relations'] = ApiClient.convertToType(data['relations'], [ContactDetailRelation]);
      }
      if (data.hasOwnProperty('diagram')) {
        obj['diagram'] = ApiClient.convertToType(data['diagram'], [Diagram]);
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [UseTag]);
      }
      if (data.hasOwnProperty('notes')) {
        obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
      }
    }
    return obj;
  }

  /**
   * 联系人关系列表
   * @member {Array.<module:model/ContactDetailRelation>} relations
   */
  exports.prototype['relations'] = undefined;
  /**
   * 收发件数量趋势图
   * @member {Array.<module:model/Diagram>} diagram
   */
  exports.prototype['diagram'] = undefined;
  /**
   * 标签列表
   * @member {Array.<module:model/UseTag>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * 批注内容
   * @member {String} notes
   */
  exports.prototype['notes'] = undefined;



  return exports;
}));


