/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.ContactDetailRelation = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContactDetailRelation model module.
   * @module model/ContactDetailRelation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ContactDetailRelation</code>.
   * @alias module:model/ContactDetailRelation
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ContactDetailRelation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactDetailRelation} obj Optional instance to populate.
   * @return {module:model/ContactDetailRelation} The populated <code>ContactDetailRelation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('contactMailBox')) {
        obj['contactMailBox'] = ApiClient.convertToType(data['contactMailBox'], 'String');
      }
      if (data.hasOwnProperty('contacCount')) {
        obj['contacCount'] = ApiClient.convertToType(data['contacCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 关系邮箱
   * @member {String} contactMailBox
   */
  exports.prototype['contactMailBox'] = undefined;
  /**
   * 关系会话总数
   * @member {Number} contacCount
   */
  exports.prototype['contacCount'] = undefined;



  return exports;
}));


