/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (false) {
        // AMD. Register as an anonymous module.
        define(['ApiClient'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'));
    } else {
        // Browser globals (root is window)
        if (!root.CInsightGui) {
            root.CInsightGui = {};
        }
        root.CInsightGui.ContactRelation = factory(root.CInsightGui.ApiClient);
    }
}(this, function(ApiClient) {
    'use strict';




    /**
     * The ContactRelation model module.
     * @module model/ContactRelation
     * @version 1.0.0
     */

    /**
     * Constructs a new <code>ContactRelation</code>.
     * @alias module:model/ContactRelation
     * @class
     */
    var exports = function() {
        var _this = this;




    };

    /**
     * Constructs a <code>ContactRelation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactRelation} obj Optional instance to populate.
     * @return {module:model/ContactRelation} The populated <code>ContactRelation</code> instance.
     */
    exports.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('mailboxId')) {
                obj['mailboxId'] = ApiClient.convertToType(data['mailboxId'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'String');
            }
        }
        return obj;
    }

    /**
     * 邮箱ID
     * @member {String} mailboxId
     */
    exports.prototype['mailboxId'] = undefined;
    /**
     * 关系人
     * @member {String} to
     */
    exports.prototype['to'] = undefined;
    /**
     * 来往邮件数
     * @member {String} count
     */
    exports.prototype['count'] = undefined;



    return exports;
}));


