/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.History = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The History model module.
   * @module model/History
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>History</code>.
   * @alias module:model/History
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>History</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/History} obj Optional instance to populate.
   * @return {module:model/History} The populated <code>History</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('historyId')) {
        obj['historyId'] = ApiClient.convertToType(data['historyId'], 'String');
      }
      if (data.hasOwnProperty('historyName')) {
        obj['historyName'] = ApiClient.convertToType(data['historyName'], 'String');
      }
      if (data.hasOwnProperty('createTime')) {
        obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 操作记录id
   * @member {String} historyId
   */
  exports.prototype['historyId'] = undefined;
  /**
   * 操作记录名称
   * @member {String} historyName
   */
  exports.prototype['historyName'] = undefined;
  /**
   * 结果集创建时间
   * @member {Number} createTime
   */
  exports.prototype['createTime'] = undefined;



  return exports;
}));


