/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.LoadReport = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoadReport model module.
   * @module model/LoadReport
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LoadReport</code>.
   * @alias module:model/LoadReport
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>LoadReport</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoadReport} obj Optional instance to populate.
   * @return {module:model/LoadReport} The populated <code>LoadReport</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('totalCount')) {
        obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
      }
      if (data.hasOwnProperty('successCount')) {
        obj['successCount'] = ApiClient.convertToType(data['successCount'], 'Number');
      }
      if (data.hasOwnProperty('failCount')) {
        obj['failCount'] = ApiClient.convertToType(data['failCount'], 'Number');
      }
      if (data.hasOwnProperty('failFiles')) {
        obj['failFiles'] = ApiClient.convertToType(data['failFiles'], ['String']);
      }
    }
    return obj;
  }

  /**
   * 数据文件总量
   * @member {Number} totalCount
   */
  exports.prototype['totalCount'] = undefined;
  /**
   * 装载成功数量
   * @member {Number} successCount
   */
  exports.prototype['successCount'] = undefined;
  /**
   * 装载失败数量
   * @member {Number} failCount
   */
  exports.prototype['failCount'] = undefined;
  /**
   * @member {Array.<String>} failFiles
   */
  exports.prototype['failFiles'] = undefined;



  return exports;
}));


