/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.MailboxStatistics = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MailboxStatistics model module.
   * @module model/MailboxStatistics
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MailboxStatistics</code>.
   * @alias module:model/MailboxStatistics
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>MailboxStatistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MailboxStatistics} obj Optional instance to populate.
   * @return {module:model/MailboxStatistics} The populated <code>MailboxStatistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('inboxCount')) {
        obj['inboxCount'] = ApiClient.convertToType(data['inboxCount'], 'Number');
      }
      if (data.hasOwnProperty('outboxCount')) {
        obj['outboxCount'] = ApiClient.convertToType(data['outboxCount'], 'Number');
      }
      if (data.hasOwnProperty('draftboxCount')) {
        obj['draftboxCount'] = ApiClient.convertToType(data['draftboxCount'], 'Number');
      }
      if (data.hasOwnProperty('trashCount')) {
        obj['trashCount'] = ApiClient.convertToType(data['trashCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 收件箱邮件数量
   * @member {Number} inboxCount
   */
  exports.prototype['inboxCount'] = undefined;
  /**
   * 发件箱邮件数量
   * @member {Number} outboxCount
   */
  exports.prototype['outboxCount'] = undefined;
  /**
   * 草稿箱邮件数量
   * @member {Number} draftboxCount
   */
  exports.prototype['draftboxCount'] = undefined;
  /**
   * 垃圾箱邮件数量
   * @member {Number} trashCount
   */
  exports.prototype['trashCount'] = undefined;



  return exports;
}));


