/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (false) {
        // AMD. Register as an anonymous module.
        define(['ApiClient'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'));
    } else {
        // Browser globals (root is window)
        if (!root.CInsightGui) {
            root.CInsightGui = {};
        }
        root.CInsightGui.MailContact = factory(root.CInsightGui.ApiClient);
    }
}(this, function (ApiClient) {
    'use strict';


    /**
     * The MailContact model module.
     * @module model/MailContact
     * @version 1.0.0
     */

    /**
     * Constructs a new <code>MailContact</code>.
     * @alias module:model/MailContact
     * @class
     */
    var exports = function () {
        var _this = this;


    };

    /**
     * Constructs a <code>MailContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailContact} obj Optional instance to populate.
     * @return {module:model/MailContact} The populated <code>MailContact</code> instance.
     */
    exports.constructFromObject = function (data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('mailAddress')) {
                obj['mailAddress'] = ApiClient.convertToType(data['mailAddress'], 'String');
            }
        }
        return obj;
    }

    /**
     * 邮箱地址
     * @member {String} mailAddress
     */
    exports.prototype['mailAddress'] = undefined;


    return exports;
}));


