/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (false) {
        // AMD. Register as an anonymous module.
        define(['ApiClient', 'model/UseTag'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'), require('./UseTag'));
    } else {
        // Browser globals (root is window)
        if (!root.CInsightGui) {
            root.CInsightGui = {};
        }
        root.CInsightGui.MailboxList = factory(root.CInsightGui.ApiClient, root.CInsightGui.UseTag);
    }
}(this, function(ApiClient, UseTag) {
    'use strict';




    /**
     * The MailboxList model module.
     * @module model/MailboxList
     * @version 1.0.0
     */

    /**
     * Constructs a new <code>MailboxList</code>.
     * @alias module:model/MailboxList
     * @class
     */
    var exports = function() {
        var _this = this;









    };

    /**
     * Constructs a <code>MailboxList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailboxList} obj Optional instance to populate.
     * @return {module:model/MailboxList} The populated <code>MailboxList</code> instance.
     */
    exports.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('mailboxId')) {
                obj['mailboxId'] = ApiClient.convertToType(data['mailboxId'], 'String');
            }
            if (data.hasOwnProperty('mailboxAddress')) {
                obj['mailboxAddress'] = ApiClient.convertToType(data['mailboxAddress'], 'String');
            }
            if (data.hasOwnProperty('inboxCount')) {
                obj['inboxCount'] = ApiClient.convertToType(data['inboxCount'], 'Number');
            }
            if (data.hasOwnProperty('outboxCount')) {
                obj['outboxCount'] = ApiClient.convertToType(data['outboxCount'], 'Number');
            }
            if (data.hasOwnProperty('draftboxCount')) {
                obj['draftboxCount'] = ApiClient.convertToType(data['draftboxCount'], 'Number');
            }
            if (data.hasOwnProperty('trashCount')) {
                obj['trashCount'] = ApiClient.convertToType(data['trashCount'], 'Number');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [UseTag]);
            }
        }
        return obj;
    }

    /**
     * 邮箱id
     * @member {String} mailboxId
     */
    exports.prototype['mailboxId'] = undefined;
    /**
     * 邮箱名称
     * @member {String} mailboxAddress
     */
    exports.prototype['mailboxAddress'] = undefined;
    /**
     * 收件箱邮件数量
     * @member {Number} inboxCount
     */
    exports.prototype['inboxCount'] = undefined;
    /**
     * 发件箱邮件数量
     * @member {Number} outboxCount
     */
    exports.prototype['outboxCount'] = undefined;
    /**
     * 草稿箱邮件数量
     * @member {Number} draftboxCount
     */
    exports.prototype['draftboxCount'] = undefined;
    /**
     * 垃圾箱邮件数量
     * @member {Number} trashCount
     */
    exports.prototype['trashCount'] = undefined;
    /**
     * 批注
     * @member {String} notes
     */
    exports.prototype['notes'] = undefined;
    /**
     * 标签列表
     * @member {Array.<module:model/UseTag>} tags
     */
    exports.prototype['tags'] = undefined;



    return exports;
}));


