/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.ModelCase = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModelCase model module.
   * @module model/ModelCase
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelCase</code>.
   * @alias module:model/ModelCase
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>ModelCase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelCase} obj Optional instance to populate.
   * @return {module:model/ModelCase} The populated <code>ModelCase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('caseId')) {
        obj['caseId'] = ApiClient.convertToType(data['caseId'], 'String');
      }
      if (data.hasOwnProperty('caseCode')) {
          obj['caseCode'] = ApiClient.convertToType(data['caseCode'], 'String');
      }
      if (data.hasOwnProperty('caseName')) {
        obj['caseName'] = ApiClient.convertToType(data['caseName'], 'String');
      }
      if (data.hasOwnProperty('lastViewTime')) {
        obj['lastViewTime'] = ApiClient.convertToType(data['lastViewTime'], 'Number');
      }
      if (data.hasOwnProperty('caseOperator')) {
        obj['caseOperator'] = ApiClient.convertToType(data['caseOperator'], 'String');
      }
      if (data.hasOwnProperty('kickoffDate')) {
        obj['kickoffDate'] = ApiClient.convertToType(data['kickoffDate'], 'Number');
      }
      if (data.hasOwnProperty('remark')) {
        obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
      }
      if (data.hasOwnProperty('mailAmount')) {
        obj['mailAmount'] = ApiClient.convertToType(data['mailAmount'], 'String');
      }
    }
    return obj;
  }

  /**
   * 案件id
   * @member {String} caseId
   */
  exports.prototype['caseId'] = undefined;
    /**
     * 案件编号
     * @member {String} caseCode
     */
    exports.prototype['caseCode'] = undefined;
  /**
   * 案件名称
   * @member {String} caseName
   */
  exports.prototype['caseName'] = undefined;
  /**
   * 最后查看时间
   * @member {Number} lastViewTime
   */
  exports.prototype['lastViewTime'] = undefined;
  /**
   * 负责人
   * @member {String} caseOperator
   */
  exports.prototype['caseOperator'] = undefined;
  /**
   * 立案日期
   * @member {Number} kickoffDate
   */
  exports.prototype['kickoffDate'] = undefined;
  /**
   * 备注
   * @member {String} remark
   */
  exports.prototype['remark'] = undefined;
  /**
   * 邮件数目
   * @member {String} mailAmount
   */
  exports.prototype['mailAmount'] = undefined;



  return exports;
}));


