/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.Plugin = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Plugin model module.
   * @module model/Plugin
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Plugin</code>.
   * @alias module:model/Plugin
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Plugin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Plugin} obj Optional instance to populate.
   * @return {module:model/Plugin} The populated <code>Plugin</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pluginId')) {
        obj['pluginId'] = ApiClient.convertToType(data['pluginId'], 'String');
      }
      if (data.hasOwnProperty('pluginName')) {
        obj['pluginName'] = ApiClient.convertToType(data['pluginName'], 'String');
      }
      if (data.hasOwnProperty('pluginDescription')) {
        obj['pluginDescription'] = ApiClient.convertToType(data['pluginDescription'], 'String');
      }
      if (data.hasOwnProperty('pluginEnabled')) {
        obj['pluginEnabled'] = ApiClient.convertToType(data['pluginEnabled'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * 插件id
   * @member {String} pluginId
   */
  exports.prototype['pluginId'] = undefined;
  /**
   * 插件名称
   * @member {String} pluginName
   */
  exports.prototype['pluginName'] = undefined;
  /**
   * 插件描述文本
   * @member {String} pluginDescription
   */
  exports.prototype['pluginDescription'] = undefined;
  /**
   * 插件是否启用
   * @member {Boolean} pluginEnabled
   */
  exports.prototype['pluginEnabled'] = undefined;



  return exports;
}));


