/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TagChild'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TagChild'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.Tag = factory(root.CInsightGui.ApiClient, root.CInsightGui.TagChild);
  }
}(this, function(ApiClient, TagChild) {
  'use strict';




  /**
   * The Tag model module.
   * @module model/Tag
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Tag</code>.
   * @alias module:model/Tag
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Tag</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tag} obj Optional instance to populate.
   * @return {module:model/Tag} The populated <code>Tag</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('typeName')) {
        obj['typeName'] = ApiClient.convertToType(data['typeName'], 'String');
      }
      if (data.hasOwnProperty('typeIcon')) {
        obj['typeIcon'] = ApiClient.convertToType(data['typeIcon'], 'String');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [TagChild]);
      }
    }
    return obj;
  }

  /**
   * 标签类型
   * @member {String} typeName
   */
  exports.prototype['typeName'] = undefined;
  /**
   * 标签图标名称
   * @member {String} typeIcon
   */
  exports.prototype['typeIcon'] = undefined;
  /**
   * 标签类型，取值=用户、信息、领域、姓名、文件
   * @member {Array.<module:model/TagChild>} tags
   */
  exports.prototype['tags'] = undefined;



  return exports;
}));


