/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.TagChild = factory(root.CInsightGui.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TagChild model module.
   * @module model/TagChild
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TagChild</code>.
   * @alias module:model/TagChild
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TagChild</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagChild} obj Optional instance to populate.
   * @return {module:model/TagChild} The populated <code>TagChild</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tagName')) {
        obj['tagName'] = ApiClient.convertToType(data['tagName'], 'String');
      }
      if (data.hasOwnProperty('hitCount')) {
        obj['hitCount'] = ApiClient.convertToType(data['hitCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 标签名称
   * @member {String} tagName
   */
  exports.prototype['tagName'] = undefined;
  /**
   * 命中数
   * @member {Number} hitCount
   */
  exports.prototype['hitCount'] = undefined;



  return exports;
}));


