/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/Lexicon'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/Lexicon'));
  } else {
    // Browser globals (root is window)
    if (!root.CInsightGui) {
      root.CInsightGui = {};
    }
    root.CInsightGui.LexiconApi = factory(root.CInsightGui.ApiClient, root.CInsightGui.Error, root.CInsightGui.Lexicon);
  }
}(this, function(ApiClient, Error, Lexicon) {
  'use strict';

  /**
   * Lexicon service.
   * @module api/LexiconApi
   * @version 1.0.0
   */

  /**
   * Constructs a new LexiconApi. 
   * @alias module:api/LexiconApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the selectLexiconOptionList operation.
     * @callback module:api/LexiconApi~selectLexiconOptionListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Lexicon>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 获取词库配置列表
     * 功能菜单获取词库配置列表
     * @param {module:api/LexiconApi~selectLexiconOptionListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Lexicon>}
     */
    this.selectLexiconOptionList = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Lexicon];

      return this.apiClient.callApi(
        '/plugin/lexicon/options', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateLexiconOptions operation.
     * @callback module:api/LexiconApi~updateLexiconOptionsCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 启用/禁用词库配置
     * 功能菜单启用/禁用词库配置，lexiconIds为要启用的词库id集合，不再此数据中的id将被禁用
     * @param {String} lexiconIds 插件id数组
     * @param {module:api/LexiconApi~updateLexiconOptionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.updateLexiconOptions = function(lexiconIds, callback) {
      var postBody = null;

      // verify the required parameter 'lexiconIds' is set
      if (lexiconIds == undefined || lexiconIds == null) {
        throw new Error("Missing the required parameter 'lexiconIds' when calling updateLexiconOptions");
      }


      var pathParams = {
      };
      var queryParams = {
        'lexiconIds': lexiconIds
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/plugin/lexicon/options', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
