/**
 * cInsight-gui
 * The Case Analysis Software
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (false) {
        // AMD. Register as an anonymous module.
        define(['ApiClient', 'model/CustomTag', 'model/Error', 'model/Tag'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'), require('../model/CustomTag'), require('../model/Error'), require('../model/Tag'));
    } else {
        // Browser globals (root is window)
        if (!root.CInsightGui) {
            root.CInsightGui = {};
        }
        root.CInsightGui.TagApi = factory(root.CInsightGui.ApiClient, root.CInsightGui.CustomTag, root.CInsightGui.Error, root.CInsightGui.Tag);
    }
}(this, function (ApiClient, CustomTag, Error, Tag) {
    'use strict';

    /**
     * Tag service.
     * @module api/TagApi
     * @version 1.0.0
     */

    /**
     * Constructs a new TagApi.
     * @alias module:api/TagApi
     * @class
     * @param {module:ApiClient} apiClient Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    var exports = function (apiClient) {
        this.apiClient = apiClient || ApiClient.instance;


        /**
         * Callback function to receive the result of the createCustomTagList operation.
         * @callback module:api/TagApi~createCustomTagListCallback
         * @param {String} error Error message, if any.
         * @param {Object} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         * 新建自定义标签
         * 新建自定义标签
         * @param {String} caseId 案件id
         * @param {String} tagName 自定义标签name
         * @param {module:api/TagApi~createCustomTagListCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link Object}
         */
        this.createCustomTagList = function (caseId, tagName, callback) {
            var postBody = null;

            // verify the required parameter 'caseId' is set
            if (caseId == undefined || caseId == null) {
                throw new Error("Missing the required parameter 'caseId' when calling createCustomTagList");
            }

            // verify the required parameter 'tagName' is set
            if (tagName == undefined || tagName == null) {
                throw new Error("Missing the required parameter 'tagName' when calling createCustomTagList");
            }


            var pathParams = {
                'caseId': caseId
            };
            var queryParams = {
                'tagName': tagName
            };
            var headerParams = {};
            var formParams = {};

            var authNames = [];
            var contentTypes = [];
            var accepts = ['application/json'];
            var returnType = Object;

            return this.apiClient.callApi(
                '/tag/customs/{caseId}', 'POST',
                pathParams, queryParams, headerParams, formParams, postBody,
                authNames, contentTypes, accepts, returnType, callback
            );
        }

        /**
         * Callback function to receive the result of the selectCustomTagList operation.
         * @callback module:api/TagApi~selectCustomTagListCallback
         * @param {String} error Error message, if any.
         * @param {Array.<module:model/CustomTag>} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         * 查询自定义标签列表
         * 查询自定义标签列表，按标签类型排序
         * @param {String} caseId 案件id
         * @param {module:api/TagApi~selectCustomTagListCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link Array.<module:model/CustomTag>}
         */
        this.selectCustomTagList = function (caseId, callback) {
            var postBody = null;

            // verify the required parameter 'caseId' is set
            if (caseId == undefined || caseId == null) {
                throw new Error("Missing the required parameter 'caseId' when calling selectCustomTagList");
            }


            var pathParams = {
                'caseId': caseId
            };
            var queryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = [];
            var contentTypes = [];
            var accepts = ['application/json'];
            var returnType = [CustomTag];

            return this.apiClient.callApi(
                '/tag/customs/{caseId}', 'GET',
                pathParams, queryParams, headerParams, formParams, postBody,
                authNames, contentTypes, accepts, returnType, callback
            );
        }

        /**
         * Callback function to receive the result of the selectTagList operation.
         * @callback module:api/TagApi~selectTagListCallback
         * @param {String} error Error message, if any.
         * @param {Array.<module:model/Tag>} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         * 查询标签列表
         * 查询标签树列表，按标签类型排序
         * @param {String} caseId 案件id
         * @param {module:api/TagApi~selectTagListCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link Array.<module:model/Tag>}
         */
        this.selectTagList = function (caseId, callback) {
            var postBody = null;

            // verify the required parameter 'caseId' is set
            if (caseId == undefined || caseId == null) {
                throw new Error("Missing the required parameter 'caseId' when calling selectTagList");
            }


            var pathParams = {
                'caseId': caseId
            };
            var queryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = [];
            var contentTypes = [];
            var accepts = ['application/json'];
            var returnType = [Tag];

            return this.apiClient.callApi(
                '/tag/{caseId}', 'GET',
                pathParams, queryParams, headerParams, formParams, postBody,
                authNames, contentTypes, accepts, returnType, callback
            );
        }
    };

    return exports;
}));
