/*
 * 案件分析系统后台引擎
 * 案件分析系统后台引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.xaeport.cinsight.ui.data.entity;


import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Mail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-31T03:30:06.203Z")
public class Mail {
    @SerializedName("mailId")
    private String mailId = null;

    @SerializedName("mailboxId")
    private String mailboxId = null;

    @SerializedName("from")
    private String from = null;

    @SerializedName("subject")
    private String subject = null;

    @SerializedName("to")
    private List<MailContact> to = new ArrayList<MailContact>();

    @SerializedName("cc")
    private List<MailContact> cc = new ArrayList<MailContact>();

    @SerializedName("bcc")
    private List<MailContact> bcc = new ArrayList<MailContact>();

    @SerializedName("sendTime")
    private Long sendTime = null;

    @SerializedName("sendTimezone")
    private Long sendTimezone = null;

    @SerializedName("mailContent")
    private String mailContent = null;

    @SerializedName("attachments")
    private List<Attachment> attachments = new ArrayList<Attachment>();

    @SerializedName("sessionCount")
    private Long sessionCount = null;

    @SerializedName("attachmentCount")
    private Long attachmentCount = null;

    @SerializedName("tagCount")
    private Long tagCount = null;

    @SerializedName("tag")
    private String tag = null;

    @SerializedName("tags")
    private List<UseTag> tags = new ArrayList<UseTag>();

    @SerializedName("note")
    private String note = null;

    @SerializedName("remark")
    private String remark = null;

    public Mail mailId(String mailId) {
        this.mailId = mailId;
        return this;
    }

    /**
     * Get mailId
     *
     * @return mailId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getMailId() {
        return mailId;
    }

    public void setMailId(String mailId) {
        this.mailId = mailId;
    }

    public Mail mailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
        return this;
    }

    /**
     * 邮箱
     *
     * @return mailboxId
     **/
    @ApiModelProperty(example = "null", value = "邮箱")
    public String getMailboxId() {
        return mailboxId;
    }

    public void setMailboxId(String mailboxId) {
        this.mailboxId = mailboxId;
    }

    public Mail from(String from) {
        this.from = from;
        return this;
    }

    /**
     * 发件人
     *
     * @return from
     **/
    @ApiModelProperty(example = "null", value = "发件人")
    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public Mail subject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * 主题
     *
     * @return subject
     **/
    @ApiModelProperty(example = "null", value = "主题")
    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Mail to(List<MailContact> to) {
        this.to = to;
        return this;
    }

    public Mail addToItem(MailContact toItem) {
        this.to.add(toItem);
        return this;
    }

    /**
     * 收件人
     *
     * @return to
     **/
    @ApiModelProperty(example = "null", value = "收件人")
    public List<MailContact> getTo() {
        return to;
    }

    public void setTo(List<MailContact> to) {
        this.to = to;
    }

    public Mail cc(List<MailContact> cc) {
        this.cc = cc;
        return this;
    }

    public Mail addCcItem(MailContact ccItem) {
        this.cc.add(ccItem);
        return this;
    }

    /**
     * 抄送
     *
     * @return cc
     **/
    @ApiModelProperty(example = "null", value = "抄送")
    public List<MailContact> getCc() {
        return cc;
    }

    public void setCc(List<MailContact> cc) {
        this.cc = cc;
    }

    public Mail bcc(List<MailContact> bcc) {
        this.bcc = bcc;
        return this;
    }

    public Mail addBccItem(MailContact bccItem) {
        this.bcc.add(bccItem);
        return this;
    }

    /**
     * 暗送
     *
     * @return bcc
     **/
    @ApiModelProperty(example = "null", value = "暗送")
    public List<MailContact> getBcc() {
        return bcc;
    }

    public void setBcc(List<MailContact> bcc) {
        this.bcc = bcc;
    }

    public Mail sendTime(Long sendTime) {
        this.sendTime = sendTime;
        return this;
    }

    /**
     * 发送时间
     *
     * @return sendTime
     **/
    @ApiModelProperty(example = "null", value = "发送时间")
    public Long getSendTime() {
        return sendTime;
    }

    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    public Mail sendTimezone(Long sendTimezone) {
        this.sendTimezone = sendTimezone;
        return this;
    }

    /**
     * 发送时区
     *
     * @return sendTimezone
     **/
    @ApiModelProperty(example = "null", value = "发送时区")
    public Long getSendTimezone() {
        return sendTimezone;
    }

    public void setSendTimezone(Long sendTimezone) {
        this.sendTimezone = sendTimezone;
    }

    public Mail mailContent(String mailContent) {
        this.mailContent = mailContent;
        return this;
    }

    /**
     * 邮件内容
     *
     * @return mailContent
     **/
    @ApiModelProperty(example = "null", value = "邮件内容")
    public String getMailContent() {
        return mailContent;
    }

    public void setMailContent(String mailContent) {
        this.mailContent = mailContent;
    }

    public Mail attachments(List<Attachment> attachments) {
        this.attachments = attachments;
        return this;
    }

    public Mail addAttachmentsItem(Attachment attachmentsItem) {
        this.attachments.add(attachmentsItem);
        return this;
    }

    /**
     * 附件列表
     *
     * @return attachments
     **/
    @ApiModelProperty(example = "null", value = "附件列表")
    public List<Attachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }

    public Mail sessionCount(Long sessionCount) {
        this.sessionCount = sessionCount;
        return this;
    }

    /**
     * 会话数量
     *
     * @return sessionCount
     **/
    @ApiModelProperty(example = "null", value = "会话数量")
    public Long getSessionCount() {
        return sessionCount;
    }

    public void setSessionCount(Long sessionCount) {
        this.sessionCount = sessionCount;
    }

    public Mail attachmentCount(Long attachmentCount) {
        this.attachmentCount = attachmentCount;
        return this;
    }

    /**
     * 附件数量
     *
     * @return attachmentCount
     **/
    @ApiModelProperty(example = "null", value = "附件数量")
    public Long getAttachmentCount() {
        return attachmentCount;
    }

    public void setAttachmentCount(Long attachmentCount) {
        this.attachmentCount = attachmentCount;
    }

    public Mail tagCount(Long tagCount) {
        this.tagCount = tagCount;
        return this;
    }

    /**
     * 标签数量
     *
     * @return tagCount
     **/
    @ApiModelProperty(example = "null", value = "标签数量")
    public Long getTagCount() {
        return tagCount;
    }

    public void setTagCount(Long tagCount) {
        this.tagCount = tagCount;
    }

    public Mail tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * 标签
     *
     * @return tag
     **/
    @ApiModelProperty(example = "null", value = "标签")
    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Mail tags(List<UseTag> tags) {
        this.tags = tags;
        return this;
    }

    public Mail addTagsItem(UseTag tagsItem) {
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * 标签
     *
     * @return tags
     **/
    @ApiModelProperty(example = "null", value = "标签")
    public List<UseTag> getTags() {
        return tags;
    }

    public void setTags(List<UseTag> tags) {
        this.tags = tags;
    }

    public Mail note(String note) {
        this.note = note;
        return this;
    }

    /**
     * 批注
     *
     * @return note
     **/
    @ApiModelProperty(example = "null", value = "批注")
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Mail remark(String remark) {
        this.remark = remark;
        return this;
    }

    /**
     * 备注
     *
     * @return remark
     **/
    @ApiModelProperty(example = "null", value = "备注")
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Mail mail = (Mail) o;
        return Objects.equals(this.mailId, mail.mailId) &&
                Objects.equals(this.mailboxId, mail.mailboxId) &&
                Objects.equals(this.from, mail.from) &&
                Objects.equals(this.subject, mail.subject) &&
                Objects.equals(this.to, mail.to) &&
                Objects.equals(this.cc, mail.cc) &&
                Objects.equals(this.bcc, mail.bcc) &&
                Objects.equals(this.sendTime, mail.sendTime) &&
                Objects.equals(this.sendTimezone, mail.sendTimezone) &&
                Objects.equals(this.mailContent, mail.mailContent) &&
                Objects.equals(this.attachments, mail.attachments) &&
                Objects.equals(this.sessionCount, mail.sessionCount) &&
                Objects.equals(this.attachmentCount, mail.attachmentCount) &&
                Objects.equals(this.tagCount, mail.tagCount) &&
                Objects.equals(this.tag, mail.tag) &&
                Objects.equals(this.tags, mail.tags) &&
                Objects.equals(this.note, mail.note) &&
                Objects.equals(this.remark, mail.remark);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mailId, mailboxId, from, subject, to, cc, bcc, sendTime, sendTimezone, mailContent, attachments, sessionCount, attachmentCount, tagCount, tag, tags, note, remark);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Mail {\n");

        sb.append("    mailId: ").append(toIndentedString(mailId)).append("\n");
        sb.append("    mailboxId: ").append(toIndentedString(mailboxId)).append("\n");
        sb.append("    from: ").append(toIndentedString(from)).append("\n");
        sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
        sb.append("    to: ").append(toIndentedString(to)).append("\n");
        sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
        sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
        sb.append("    sendTime: ").append(toIndentedString(sendTime)).append("\n");
        sb.append("    sendTimezone: ").append(toIndentedString(sendTimezone)).append("\n");
        sb.append("    mailContent: ").append(toIndentedString(mailContent)).append("\n");
        sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
        sb.append("    sessionCount: ").append(toIndentedString(sessionCount)).append("\n");
        sb.append("    attachmentCount: ").append(toIndentedString(attachmentCount)).append("\n");
        sb.append("    tagCount: ").append(toIndentedString(tagCount)).append("\n");
        sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    note: ").append(toIndentedString(note)).append("\n");
        sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

