/*
 * 案件分析引擎
 * 案件分析引擎
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cinsight@xaeport.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.xaeport.cinsight.ui.engine.api;

import com.google.gson.reflect.TypeToken;
import com.xaeport.cinsight.ui.engine.*;
import com.xaeport.cinsight.ui.engine.model.ResponseData;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NoteApi {
    private ApiClient apiClient;

    public NoteApi() {
        this(Configuration.getDefaultApiClient());
    }

    public NoteApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for updateNoteByObjectTypeAndId */
    private com.squareup.okhttp.Call updateNoteByObjectTypeAndIdCall(Integer objType, String objId, String notes, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/note".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (objType != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "objType", objType));
        if (objId != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "objId", objId));
        if (notes != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "notes", notes));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call updateNoteByObjectTypeAndIdValidateBeforeCall(Integer objType, String objId, String notes, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'objType' is set
        if (objType == null) {
            throw new ApiException("Missing the required parameter 'objType' when calling updateNoteByObjectTypeAndId(Async)");
        }
        
        // verify the required parameter 'objId' is set
        if (objId == null) {
            throw new ApiException("Missing the required parameter 'objId' when calling updateNoteByObjectTypeAndId(Async)");
        }
        
        // verify the required parameter 'notes' is set
        if (notes == null) {
            throw new ApiException("Missing the required parameter 'notes' when calling updateNoteByObjectTypeAndId(Async)");
        }
        
        
        com.squareup.okhttp.Call call = updateNoteByObjectTypeAndIdCall(objType, objId, notes, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 批注
     * 对对象进行内容批注
     * @param objType 批注对象类型 [0 案件 1 邮件 2 附件 3 联系人] (required)
     * @param objId 批注对象ID (required)
     * @param notes 批注信息 (required)
     * @return ResponseData
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ResponseData updateNoteByObjectTypeAndId(Integer objType, String objId, String notes) throws ApiException {
        ApiResponse<ResponseData> resp = updateNoteByObjectTypeAndIdWithHttpInfo(objType, objId, notes);
        return resp.getData();
    }

    /**
     * 批注
     * 对对象进行内容批注
     * @param objType 批注对象类型 [0 案件 1 邮件 2 附件 3 联系人] (required)
     * @param objId 批注对象ID (required)
     * @param notes 批注信息 (required)
     * @return ApiResponse&lt;ResponseData&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ResponseData> updateNoteByObjectTypeAndIdWithHttpInfo(Integer objType, String objId, String notes) throws ApiException {
        com.squareup.okhttp.Call call = updateNoteByObjectTypeAndIdValidateBeforeCall(objType, objId, notes, null, null);
        Type localVarReturnType = new TypeToken<ResponseData>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 批注 (asynchronously)
     * 对对象进行内容批注
     * @param objType 批注对象类型 [0 案件 1 邮件 2 附件 3 联系人] (required)
     * @param objId 批注对象ID (required)
     * @param notes 批注信息 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call updateNoteByObjectTypeAndIdAsync(Integer objType, String objId, String notes, final ApiCallback<ResponseData> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = updateNoteByObjectTypeAndIdValidateBeforeCall(objType, objId, notes, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ResponseData>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
